# -*- coding: utf-8 -*-
"""Catálogo de seções e blocos do relatório +55.

Gerado em 17/09/2026 por ferramentas/extrair_catalogo.py a partir do Kit (tag gabarito-v1).
Daqui em diante é mantido À MÃO e só muda por commit: é a estrutura do relatório.

Bloco: id imutável · secao · titulo · bases (de quais dados depende) · nomes_pf (exibe nome
de pessoa; sem o recurso o nome sai mascarado) · vigencia (aaaa-mm em que passou a existir)
· depende_de (liberar este bloco libera também estes).
Regra: mudou o significado do número -> bloco novo; mudou só a forma -> nova vigência.
"""

SECOES = [{'id': 'resumo', 'titulo': 'Sumário', 'grupo': 'Comercial', 'bases': ['DATA', 'DRE', 'DPNL', 'METAS']},
 {'id': 'evolutiva', 'titulo': 'Evolutiva histórica', 'grupo': 'Comercial', 'bases': ['DATA', 'DRE']},
 {'id': 'ytd', 'titulo': 'Comparativo YTD', 'grupo': 'Comercial', 'bases': ['DATA']},
 {'id': 'mensal', 'titulo': 'Análise mensal', 'grupo': 'Comercial', 'bases': ['DATA']},
 {'id': 'periodo', 'titulo': 'Análise por período', 'grupo': 'Comercial', 'bases': ['DATA', 'DRE']},
 {'id': 'performance', 'titulo': 'Performance Comercial', 'grupo': 'Comercial', 'bases': ['DATA', 'METAS']},
 {'id': 'vendas', 'titulo': 'Análise de Vendas', 'grupo': 'Comercial', 'bases': ['DATA']},
 {'id': 'arquitetos', 'titulo': 'Vendedor × Arquiteto', 'grupo': 'Comercial', 'bases': ['DATA']},
 {'id': 'carteira', 'titulo': 'Carteira', 'grupo': 'Comercial', 'bases': ['DATA', 'CARTDIN']},
 {'id': 'carteira_dinamica', 'titulo': 'Carteira dinâmica', 'grupo': 'Comercial', 'bases': ['CARTDIN']},
 {'id': 'dre', 'titulo': 'DRE — Resultado', 'grupo': 'Gestão', 'bases': ['DPNL', 'DRE']},
 {'id': 'custofixo', 'titulo': 'Custo Fixo', 'grupo': 'Gestão', 'bases': ['CF']},
 {'id': 'custofixo_mensal', 'titulo': 'Custo Fixo — Mensal', 'grupo': 'Gestão', 'bases': ['CFMENSAL']},
 {'id': 'divida', 'titulo': 'Dívida e endividamento', 'grupo': 'Gestão', 'bases': ['DPNL', 'DRE', 'APORTES']},
 {'id': 'custosx', 'titulo': 'Custos — Executivo', 'grupo': 'Fábrica', 'bases': ['CUSTOS']},
 {'id': 'custos', 'titulo': 'Custos — Operacional', 'grupo': 'Fábrica', 'bases': ['CUSTOS']},
 {'id': 'estudos', 'titulo': 'Estudos e Análises', 'grupo': 'Gestão', 'bases': ['FABLOJA']}]

BLOCOS = [{'id': 'resumo.abertura',
  'secao': 'resumo',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA', 'DRE', 'DPNL', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'rs-hist',
  'secao': 'resumo',
  'titulo': 'Histórico completo',
  'bases': ['DATA', 'DRE', 'DPNL', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'rs-ytd',
  'secao': 'resumo',
  'titulo': 'Ano corrente até o último mês',
  'bases': ['DATA', 'DRE', 'DPNL', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'rs-leitura',
  'secao': 'resumo',
  'titulo': 'Leitura executiva',
  'bases': ['DATA', 'DRE', 'DPNL', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'evolutiva.abertura',
  'secao': 'evolutiva',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ev-anual',
  'secao': 'evolutiva',
  'titulo': 'Venda contratada × faturamento (DRE) — anual',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ytd.abertura',
  'secao': 'ytd',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ytd-kpi',
  'secao': 'ytd',
  'titulo': 'Indicadores do topo',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ytd-linha',
  'secao': 'ytd',
  'titulo': 'Curva mês a mês — ano corrente × anterior',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ytd-ind',
  'secao': 'ytd',
  'titulo': 'Tabela de indicadores',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ytd-vendedor',
  'secao': 'ytd',
  'titulo': 'Variação por vendedor(a)',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'mensal.abertura',
  'secao': 'mensal',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'mn-evol',
  'secao': 'mensal',
  'titulo': 'Evolução — 12 meses até o mês escolhido',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'mn-vend',
  'secao': 'mensal',
  'titulo': 'Top vendedoras',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'mn-cat',
  'secao': 'mensal',
  'titulo': 'Top categorias',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'mn-cli',
  'secao': 'mensal',
  'titulo': 'Maiores clientes do mês',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'periodo.abertura',
  'secao': 'periodo',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-cart',
  'secao': 'periodo',
  'titulo': 'Carteira em aberto — posição mês a mês',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-vend',
  'secao': 'periodo',
  'titulo': 'Desempenho por vendedor(a)',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-cat',
  'secao': 'periodo',
  'titulo': 'Categorias (famílias de produto)',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-catvend',
  'secao': 'periodo',
  'titulo': 'Principais categorias por vendedor(a)',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-canal',
  'secao': 'periodo',
  'titulo': 'Clientes e canal',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-cli',
  'secao': 'periodo',
  'titulo': 'Maiores clientes do período',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-desig',
  'secao': 'periodo',
  'titulo': 'Designers — royalties pagos',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-arq',
  'secao': 'periodo',
  'titulo': 'Arquitetos — RT paga',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'pe-repasses',
  'secao': 'periodo',
  'titulo': 'Composição de repasses e comissões',
  'bases': ['DATA', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'performance.abertura',
  'secao': 'performance',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'perf-acum',
  'secao': 'performance',
  'titulo': 'Vendas realizadas vs. orçamento — acumulado',
  'bases': ['DATA', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'perf-mes',
  'secao': 'performance',
  'titulo': 'Vendas realizadas vs. orçamento — mês a mês',
  'bases': ['DATA', 'METAS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'vendas.abertura',
  'secao': 'vendas',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-time',
  'secao': 'vendas',
  'titulo': 'O time no período',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-lider',
  'secao': 'vendas',
  'titulo': 'Retrato de LUCIANA FERREIRA',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-diferenca',
  'secao': 'vendas',
  'titulo': 'De onde vem a diferença',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-mix',
  'secao': 'vendas',
  'titulo': 'O que cada um vende',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-jogo',
  'secao': 'vendas',
  'titulo': 'O que está em jogo',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-rfv',
  'secao': 'vendas',
  'titulo': 'Carteira de clientes · RFV',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-parados',
  'secao': 'vendas',
  'titulo': 'Clientes de valor que pararam de comprar',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'av-qualidade',
  'secao': 'vendas',
  'titulo': 'Qualidade da carteira por vendedor(a)',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'arquitetos.abertura',
  'secao': 'arquitetos',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-peso',
  'secao': 'arquitetos',
  'titulo': 'O peso do canal',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-dependencia',
  'secao': 'arquitetos',
  'titulo': 'Quanto cada vendedor depende do canal',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-quantos',
  'secao': 'arquitetos',
  'titulo': 'De quantos arquitetos cada vendedor vive',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-matriz',
  'secao': 'arquitetos',
  'titulo': 'Quem trabalha com quem',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-lista',
  'secao': 'arquitetos',
  'titulo': 'Os arquitetos',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-parados',
  'secao': 'arquitetos',
  'titulo': 'Arquitetos que pararam de trazer',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-rfv',
  'secao': 'arquitetos',
  'titulo': 'Carteira de arquitetos · RFV',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'aq-esforco',
  'secao': 'arquitetos',
  'titulo': 'O esforço comercial de cada um',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'so_apresentacao': True,
  'depende_de': []},
 {'id': 'aq-recorrencia',
  'secao': 'arquitetos',
  'titulo': 'Quanto da carteira de arquitetos repete',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'so_apresentacao': True,
  'depende_de': []},
 {'id': 'aq-perf',
  'secao': 'arquitetos',
  'titulo': 'Performance do vendedor com o arquiteto',
  'bases': ['DATA'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'carteira.abertura',
  'secao': 'carteira',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DATA', 'CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ce-status',
  'secao': 'carteira',
  'titulo': 'Classificação da carteira por status',
  'bases': ['DATA', 'CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ce-vend',
  'secao': 'carteira',
  'titulo': 'Carteira por vendedor(a)',
  'bases': ['DATA', 'CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'ce-peds',
  'secao': 'carteira',
  'titulo': 'Maiores pedidos em carteira',
  'bases': ['DATA', 'CARTDIN'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'carteira_dinamica.abertura',
  'secao': 'carteira_dinamica',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-status',
  'secao': 'carteira_dinamica',
  'titulo': 'Classificação da carteira por status',
  'bases': ['CARTDIN'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-evol',
  'secao': 'carteira_dinamica',
  'titulo': 'Evolutiva mensal da carteira',
  'bases': ['CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-adiados',
  'secao': 'carteira_dinamica',
  'titulo': 'Carteira de pedidos adiados',
  'bases': ['CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-previsao',
  'secao': 'carteira_dinamica',
  'titulo': 'Previsão de faturamento — pedidos em andamento',
  'bases': ['CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-vend',
  'secao': 'carteira_dinamica',
  'titulo': 'Carteira por vendedor(a)',
  'bases': ['CARTDIN'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-peds',
  'secao': 'carteira_dinamica',
  'titulo': 'Maiores pedidos em carteira',
  'bases': ['CARTDIN'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cd-status-tab',
  'secao': 'carteira_dinamica',
  'titulo': 'Pedidos por status',
  'bases': ['CARTDIN'],
  'nomes_pf': True,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre.abertura',
  'secao': 'dre',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-ponte',
  'secao': 'dre',
  'titulo': 'Ponte do resultado — da receita líquida ao resultado',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-tabela',
  'secao': 'dre',
  'titulo': 'Demonstração de resultado (DRE)',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-breakeven',
  'secao': 'dre',
  'titulo': 'Ponto de equilíbrio',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-minidre',
  'secao': 'dre',
  'titulo': 'Mini-DRE — comprovação do ponto de equilíbrio',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-evol',
  'secao': 'dre',
  'titulo': 'Evolução mensal — receita líquida e EBITDA',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-produto',
  'secao': 'dre',
  'titulo': 'Ticket médio, custo e margem por produto',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-produto-ano',
  'secao': 'dre',
  'titulo': 'Histórico anual — indicadores por produto',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-fabloja',
  'secao': 'dre',
  'titulo': 'Segregação Fábrica × Loja no período',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dre-snap',
  'secao': 'dre',
  'titulo': 'Demonstração de resultado — comparativo',
  'bases': ['DPNL', 'DRE'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'custofixo.abertura',
  'secao': 'custofixo',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['CF'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cf-cat',
  'secao': 'custofixo',
  'titulo': 'Custo fixo por categoria — últimos 12 meses',
  'bases': ['CF'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cf-ent',
  'secao': 'custofixo',
  'titulo': 'Custo fixo total por entidade — Fábrica × Loja',
  'bases': ['CF'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'custofixo_mensal.abertura',
  'secao': 'custofixo_mensal',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['CFMENSAL'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cfm-pacotes',
  'secao': 'custofixo_mensal',
  'titulo': 'Pacotes de custo fixo do mês',
  'bases': ['CFMENSAL'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'divida.abertura',
  'secao': 'divida',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['DPNL', 'DRE', 'APORTES'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dv-saldo',
  'secao': 'divida',
  'titulo': 'Saldo da dívida com o acionista',
  'bases': ['DPNL', 'DRE', 'APORTES'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dv-ano',
  'secao': 'divida',
  'titulo': 'Evolução ano a ano',
  'bases': ['DPNL', 'DRE', 'APORTES'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dv-endiv',
  'secao': 'divida',
  'titulo': 'Endividamento gerado — acumulado',
  'bases': ['DPNL', 'DRE', 'APORTES'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dv-juros',
  'secao': 'divida',
  'titulo': 'Custo financeiro — juros passivos a terceiros',
  'bases': ['DPNL', 'DRE', 'APORTES'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'dv-geracao',
  'secao': 'divida',
  'titulo': 'Geração de endividamento mês a mês',
  'bases': ['DPNL', 'DRE', 'APORTES'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'custosx.abertura',
  'secao': 'custosx',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-grp',
  'secao': 'custosx',
  'titulo': 'CPV por grupo de produtos',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-ranking',
  'secao': 'custosx',
  'titulo': 'Ranking de produtos vendidos - CPV',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-mensal',
  'secao': 'custosx',
  'titulo': 'CPV mensal — composição',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-unidade',
  'secao': 'custosx',
  'titulo': 'CPV médio por unidade',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-volume',
  'secao': 'custosx',
  'titulo': 'Volume vendido (un.)',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-grupos',
  'secao': 'custosx',
  'titulo': 'Onde o CPV se concentra',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-drivers',
  'secao': 'custosx',
  'titulo': 'Drivers de Impacto no CPV',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-materia',
  'secao': 'custosx',
  'titulo': 'Composição da matéria-prima no CPV',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-operacionais',
  'secao': 'custosx',
  'titulo': 'Custos Operacionais no CPV',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-absorcao-cc',
  'secao': 'custosx',
  'titulo': 'Absorção por centro de custo no CPV',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-absorcao-conta',
  'secao': 'custosx',
  'titulo': 'Absorção por tipo de conta no CPV',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-evitavel',
  'secao': 'custosx',
  'titulo': 'Custo evitável — retrabalho e assistência técnica',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-retrabalho',
  'secao': 'custosx',
  'titulo': 'Custo de retrabalho',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-retrabalho-pareto',
  'secao': 'custosx',
  'titulo': 'Pareto de retrabalho por centro de custo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-assistencia',
  'secao': 'custosx',
  'titulo': 'Custo de assistência técnica',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cx-assistencia-prod',
  'secao': 'custosx',
  'titulo': 'Maiores custos de assistência técnica por produto',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'custos.abertura',
  'secao': 'custos',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-painel',
  'secao': 'custos',
  'titulo': 'Painel de indicadores — visão executiva',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-desmembrado',
  'secao': 'custos',
  'titulo': 'Custo de Produção Desmembrado — CPP',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-composicao',
  'secao': 'custos',
  'titulo': 'Composição do Custo de Produção - CPP',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-grupos',
  'secao': 'custos',
  'titulo': 'CPP por grupo de produtos',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-ranking',
  'secao': 'custos',
  'titulo': 'Ranking de produtos produzidos - CPP',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-volume',
  'secao': 'custos',
  'titulo': 'Volume de produção por grupo de produto',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-operacionais',
  'secao': 'custos',
  'titulo': 'Custos operacionais — Apoio × Produtivo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-produtivo',
  'secao': 'custos',
  'titulo': 'Produtivo — por tipo de conta',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-apoio',
  'secao': 'custos',
  'titulo': 'Apoio / Auxiliar — por tipo de conta',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-absorcao-conta',
  'secao': 'custos',
  'titulo': 'Absorção de custo por tipo de conta',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-absorcao-cc',
  'secao': 'custos',
  'titulo': 'Absorção por centro de custo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-cc-total',
  'secao': 'custos',
  'titulo': 'Custo total absorvido',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-cc-taxa',
  'secao': 'custos',
  'titulo': 'Taxa hora (R$/h)',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-retrabalho',
  'secao': 'custos',
  'titulo': 'Custo de retrabalho',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-retrabalho-pareto',
  'secao': 'custos',
  'titulo': 'Pareto de retrabalho por centro de custo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-assistencia',
  'secao': 'custos',
  'titulo': 'Custo de assistência técnica',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-assistencia-prod',
  'secao': 'custos',
  'titulo': 'Maiores custos de assistência técnica por produto',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-nivelzero',
  'secao': 'custos',
  'titulo': 'Abertura de Custo — Nível Zero',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-evolutivo',
  'secao': 'custos',
  'titulo': 'Evolutivo Custo de Produção — Prod. Acab. (R$/Un.)',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-comparativo',
  'secao': 'custos',
  'titulo': 'Comparativo de períodos',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-cpp-grupo',
  'secao': 'custos',
  'titulo': 'CPP/unidade por grupo',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'cu-mp-cat',
  'secao': 'custos',
  'titulo': 'Matéria-prima por categoria',
  'bases': ['CUSTOS'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'estudos.abertura',
  'secao': 'estudos',
  'titulo': 'Abertura — título, indicadores e resumo',
  'bases': ['FABLOJA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []},
 {'id': 'est-dre',
  'secao': 'estudos',
  'titulo': 'O DRE por unidade',
  'bases': ['FABLOJA'],
  'nomes_pf': False,
  'vigencia': '2026-07',
  'depende_de': []}]
